### ISSUE TITLE
Install package on laravel below 5.3

### ISSUE THREAD

**Issue by azakharow** [cariboufute/locale-route#1]
Hi, @cariboufute, you wrote that package should work with laravel 5.1 and 5.2, but I can't install it via composer since you lock 5.3 for laravel version in composer requirements. Maybe create another branch for laravel below 5.3?

**Comment by cariboufute** [comment]
@azakharow Thanks for your interest! I'll test it right now with a 5.1 Laravel installation, then if it works, will lower the Laravel version in the package.

Please wait a few hours...

**Comment by cariboufute** [comment]
@azakharow I just changed the Laravel requirements in the package to ">=5.1.0". I did not have time to test it at the moment. Could you check if everything works under Laravel 5.1?

**Comment by azakharow** [comment]
@cariboufute Thank you, but I still unable to install package because of lock on laravel 5.3v minimum requirements of your package. I guess that's because composer.lock file still has laravel 5.3 requirement.

There is my terminal output to be prooved:

```
composer require cariboufute/locale-route 1.0.0-beta
```

```
  Problem 1
    - Installation request for cariboufute/locale-route 1.0.0-beta -> satisfiable by cariboufute/locale-route[1.0.0-beta].
    - cariboufute/locale-route 1.0.0-beta requires laravel/framework 5.3.* -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.3, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
```

**Comment by cariboufute** [comment]
Try `composer require cariboufute/locale-route dev-master` for the moment. You will be sure to have the latest version with Laravel 5.1 requirement.

**Comment by enstain** [comment]
Thanks, this did the trick
