### ISSUE TITLE
Chaining problem.

### ISSUE THREAD

**Issue by timkolm** [cariboufute/locale-route#12]
How can one chain routes with for ex. ->where('sublevels', '(.*)'); ?
I could do that with Laravel's Route::get(....)->where(...);

**Comment by cariboufute** [comment]
This is not implemented yet. I will add it as a project. I think the _LocaleRoute::get, post..._ methods will return collections of Routes that will pass any chained function to each item of the collection

**Comment by cariboufute** [comment]
This is done with version 1.4.0
