### ISSUE TITLE
Named routes do not work?

### ISSUE THREAD

**Issue by gavinhewitt** [cariboufute/locale-route#14]
**Describe the bug**
Named routes don't seem to work

**To Reproduce**
Change Route:: to LocaleRoute::

**Expected behavior**
Expecting to see the homepage

**Screenshots**

**Desktop (please complete the following information):**
OSX, Chrome latest

**Smartphone (please complete the following information):**

**Additional context**
Hi, I want to convert all my routes to use LocaleRoute but this gives me a 404 if I visit the page. Also, PHPStorm highlights 'name' method as not present on Cariboufute RouteCollection. Do named routes not work anymore or did I miss something?

```
// Works
Route::get('/',
    'MainController@getHome'
)->name('home');
```

```
// Broken, returns 404
LocaleRoute::get('/',
    'MainController@getHome'
)->name('home');
```

**Comment by gavinhewitt** [comment]
I think I have figured it out. The confusing bit is that where the first parameter of Laravel Route::get() is the url, the first parameter of LocaleRoute::get() is the route name, and you pass in the url in the options array, or in my case, the routes lang file. Correct?

It seems to work now, hopefully I can start testing properly (I'm converting from Mcamara/LaravelLocalization)!

**Comment by cariboufute** [comment]
@gavinhewitt Exactly, LocaleRoute::get() (and post, put, patch, etc.) differs from Route::get() by the first argument being the route name. Route name is mandatory to make the whole system work.

Don't hesitate to write back for any question!

**Comment by gavinhewitt** [comment]
Thanks! I converted everything but for some reason 'add_locale_to_url' => false, is not working for me. I get 'Route [home] not defined.' Any idea?

**Comment by gavinhewitt** [comment]
Never mind, I was expecting this setting to do something else. I was hoping it would do the same as laravellocalization.hideDefaultLocaleInURL. Is there a way to achieve that?

**Comment by cariboufute** [comment]
Not like in LaravelLocalization, and personally I don't recommand this URL setup, since to always have the locale included in the URL will make more consistent URLs. The default locale in your site won't be necessarily in English!

You can make a workaround using normal Laravel Route for default locale and use LocaleRoute for the other locales. You can bypass the locale config by putting them into the method. Please check the documentation for this.
