### ISSUE TITLE
Cannot handle automatic generation of translated routes in web.php 

### ISSUE THREAD

**Issue by recordpcs** [cariboufute/locale-route#28]
Hello!
I have a fresh laravel 8 installation and I installed the package. I did not test on different laravel version.
I am trying to automatically create translated routes using this package, but I get into trouble: always on the same route name I get one to many URIs, some of then badly named.
I am using` php artisan route:list` to get the result.
In case I write each route without any loop on web.php all routes are properly created and work.
In my below example there are two locales, en and ro.
Below are the behaviors I faced.
_angajati_ word in romanian means _employees_ in english.

```
First result -- loop inside web.php
// this is not fine, as it doubles the routes
// there are various multiplied URIs | Name: 
// - employees/employees | en.employees.index 
// - employees/routes.employees.index | en.employees.index
// - angajati/routes.employees.index  | en.employees.index
// - angajati/angajati | ro.employees.index

foreach(['ro', 'en'] as $locale){
    Route::prefix(trans('routes.employees',[], $locale))->group(function() use($locale){
        LocaleRoute::get('employees.index', 'App\Http\Controllers\StefanController@index',
[
    $locale => trans('routes.employees',[], $locale),
]);
    });
}
```

Second result -- static writing
```
// this works fine
// routes (URI | Name): employees/angajati | ro.employees.index and employees/employees | en.employees.index
Route::prefix(trans('routes.employees',[], 'en'))->group(function(){
    LocaleRoute::get('employees.index', 'App\Http\Controllers\StefanController@index',
    [
        'en' => trans('routes.employees',[], 'en'),
        'ro' => trans('routes.employees',[], 'ro'),
    ]);
});
```

Third result -- static writing

```
// this works fine
// routes (URI | Name): angajati | ro.employees.index and employees | en.employees.index
LocaleRoute::get('employees.index', 'App\Http\Controllers\StefanController@index',
    [
        'en' => trans('routes.employees',[], 'en'),
        'ro' => trans('routes.employees',[], 'ro'),
    ]
    );
```

```
// translated files are
// EN
return [
	'employees' => 'employees',
	'edit' => 'edit',
	'create' => 'create',
];
// RO
return [
    'employees' => 'angajati',
	'edit' => 'editare',
    'create' => 'creaza',
];
```

As much I tried to identify myself the cause of these results I get to improper results.
Please advice.
Thanks for the support!

**Comment by cariboufute** [comment]
Hello!

For your first example, it is normal that you get those duplicated routes, because _LocaleRoute_ always make one route by locale. 

This explains why you have four routes In your example. you have twice the locale loop: one you do yourself (`foreach(['ro', 'en'] as $locale)`) and one done by _LocaleRoute_.

I don't have a quick solution for your problem, beside not using _prefix_ and use one _LocaleRoute_ for the whole route definition.
