### ISSUE TITLE
Unable to use middleware on separate LocaleRoute definition

### ISSUE THREAD

**Issue by enstain** [cariboufute/locale-route#3]
## Detailed description

Usually, we are able to chain methods on Route declaration, for e.g.
```php
Route::get('register', 'AccountController@register')->middleware('guest');
```

But if I call LocaleRoute with middleware
```php
LocaleRoute::get('register', 'AccountController@register')->middleware('guest');
```

I'll get following error
```bash
Call to a member function middleware() on null
```

## Possible implementation

I found solution by wrapping necessary routes into simple Route::group with including middleware as param:

```php
Route::group(['middleware' => 'guest'], function() {
    LocaleRoute::get('register', 'AccountController@register');
});
```

But it's not so DRY and LocaleRoute could return closure object to implement such usual things with routing

## My environment

* PHP 7.0
* Laravel 5.2.45

**Comment by cariboufute** [comment]
The reason why we have this error is that LocaleRoute::method does not return anything. Another thing is that middleware method is already used to set session locale.

The `group` workaround is good at the moment, but I will think about how to implement middleware in an intuitive way. If it is possible to use `->middleware()`, that would be it. If not, I would code the possibility to add a 'middleware' value in the third argument array for urls.

**Comment by cariboufute** [comment]
I added the middleware feature. You can add middleware by adding a 'middleware' key in the url array (3rd parameter).

``` php
LocaleRoute::get('route', 'Controller@getAction', ['fr' => 'url_fr', 'en' => 'url_en', 'middleware' => 'guest']);

//To use trans files URL, just add 'middleware'
LocaleRoute::get('route', 'Controller@getAction', ['middleware' => 'guest']);
```

It is under the tag 1.0.0-beta2. Please change your composer.json file accordingly (or use dev-master).
