### ISSUE TITLE
Url helpers pick up params from current route by default

### ISSUE THREAD

**Issue by enstain** [cariboufute/locale-route#6]
## Detailed description

As you described at readme, I have to call "other_route('article', [])" to get clear url without current params. But my expectation from result of url helper is to get clear route if I didn't define parameters array.

For example, let's define route with url like "path/{this_page_param}". On this page I call "other_route('another_page_route')". So, the helper generates url like "another_page_path?this_page_param=current_value". It's unexpected behaviour by my mind.

## Context

I have no idea why it should be default behaviour to keep url params from current route. When we call url helpers on page, there are links to various pages which are not connected with current page usually. And for very special situations we could pick up url params from current route (I find only one case by my mind: pagination for search results page, but it also requires finetuning, because it should keep current params but change param which defines current page).

## Possible implementation

I'd like to have separate helper with name like "other_route_with_current_params" which evidently will pick up url params from current route. Also, such helper should replace params if I define it in "parameters" array (for e.g. search results pagination, as I described above). I suggest that it should be default other_route`s behaviour to return clear route without url params from current route.

**Comment by cariboufute** [comment]
I meant to have consistency with "other_locale" but actually it doesn't have any practical usage for "other_route" to keep default parameters. I will remove this default behavior once I get back home.

**Comment by cariboufute** [comment]
Imported your branch to change this behavior...

**Comment by cariboufute** [comment]
Fixed the feature. Now _other_route_ has no parameters by default.
