### ISSUE TITLE
Translate complex uri of nested route

### ISSUE THREAD

**Issue by enstain** [cariboufute/locale-route#8]
LocaleRoute::group doesn't pick up translations from routes.php lang file, as I understand. It just adds locale code prefix before uri, but I want to translate all uri parts.

So, working recipe is very WET. I have to define LocaleRoute::get with full path for each route:

```php
app/Http/routes.php:

Route::group([
  'namespace'   => 'Backend', 
  ...
  ], function() {

      LocaleRoute::get(
        'Backend:Investments.ongoing',
        'InvestmentsController@ongoing'
      );

      LocaleRoute::get(
        'Backend:Investments.agreement',
        'InvestmentsController@agreement'
      );

});
```

And then I define translation of full uri for each route:
```php
lang/en/routes.php:

'Backend:Investments' => [
    'ongoing' => 'backend-locale/investments-locale/ongoing-locale',
    'agreement' => 'backend-locale/investments-locale/agreement-locale',
],
```

My expectation from route groups localization is that I define the hierarchy of routes like 
```php
app/Http/routes.php:
['as' => 'foo'], function() {
    ['as' => 'bar'], function() {
       ['as' => 'baz'], function() {}
    }
}
``` 
and then define translation of each uri part. But it seems impossible too, because routes.php should contain each translation from collection of routes ["foo", "foo.bar", "foo.bar.baz"] to know how construct every localized path "en/foo-locale", "en/foo-locale/bar-locale", "en/foo-locale/bar-locale/baz-locale". One possible way I see to implement such thing is to complicate routes.php lang file structure:

```php
lang/en/routes.php:

'foo' => [
    'uri' => 'foo-locale',
    'children' => [
        'bar' => [
            'uri' => 'bar-locale',
            'children' => [
                 'baz' => 'baz-locale'
            ]
        ]
    ]
]
```

But, of course, there is also a lot of work with parsing such structure and find required locale uri by route name, so it's your vote whether such thing is important or not.

**Comment by cariboufute** [comment]
At a first glance, the solution would be to implement a new router which would read the locale prefix of the group, then check the translated URL in lang/[locale]/routes.php to call the Laravel Router with the right URL.

So the routes could be written with an *UnlocaleRoute* façade (name to be changed), like this:
 
``` php
LocaleRoute::group([], function () {
    UnlocaleRoute::('index', 'Controller@index');
    UnlocaleRoute::('show', 'Controller@show');
});
```

...with the same syntax as LocaleRoute.

Again, this would need new fiddling, so don't expect a solution in the next few days. Why not try it yourself?

**Comment by enstain** [comment]
Of course, I see a lot of work here and I will try, but at first wanted to discuss right way of solution

**Comment by cariboufute** [comment]
@enstain Yes, and you did well :) Please work from _develop_ branch and merge in it, to keep _master_ branch always functional

**Comment by cariboufute** [comment]
Ok, added a *SubRoute* façade to be used under *LocaleRoute::group*, the same way you would use *LocaleGroup::get/post/etc.*

``` php
LocaleRoute::group([], function () {
    SubRoute::('index', 'Controller@index');
    SubRoute::('show', 'Controller@show');
});
```

Please check the *develop* branch.

**Comment by cariboufute** [comment]
It is now pushed into *master* branch.

**Comment by cariboufute** [comment]
With beta5 version, all you need to do now is to use LocaleRoute inside a normal Route::group method.

``` php
Route::group([], function () {
    LocaleRoute::('index', 'Controller@index');
    LocaleRoute::('show', 'Controller@show');
});
```
